### PR TITLE
Fix Status bar message v-alignment and use monospaced font for Time.

### LINKED ISSUE #78: Current time indicator in the toolbar doesn't have a fixed width
The current time indicator in the toolbar should have a fixed width and/or use a monospace font, so as to prevent the other controls from moving around when the time changes.

### PR DESCRIPTION
**Pull request by nevack**
Fixes #78 and #80

image

### CODE REVIEW

File: Window/TimeField.m [hunk 1]
```diff
@@ -8,48 +8,57 @@
...
+@implementation TimeField {
+    BOOL showTimeRemaining;
+    NSDictionary *fontAttributes;
+}
 
 - (void)awakeFromNib
 {
-    showTimeRemaining = [[NSUserDefaults standardUserDefaults] boolForKey:@"timerShowTimeRemaining"];
+    showTimeRemaining = [[NSUserDefaults standardUserDefaults] boolForKey:kTimerModeKey];
+    if (@available(macOS 10.15, *)) {
```
Comment (nevack) [inline Window/TimeField.m:25]: Should still look better than previously on pre-Catalina

Comment (kode54) [reply Window/TimeField.m:25]: Hmm, I didn't know that required Catalina. Oh well, better than nothing.
